spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jirasyncdb.cfppua5tmn1g.us-west-2.rds.amazonaws.com:3306/escuela_java_2024
    username: usuario
    password: password

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/